//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiSistemaEducativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia_estudiante
    {
        public int IDestudiante_materia { get; set; }
        public int IDestudiante { get; set; }
        public int IDmateria { get; set; }
    
        public virtual materia materia { get; set; }
        public virtual estudiante estudiante { get; set; }
    }
}
